# Generated by Django 3.2.7 on 2022-02-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_auto_20220224_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment1',
        ),
    ]
