# Generated by Django 3.2.7 on 2022-02-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='video',
            new_name='Image',
        ),
    ]
